version: '3'
services:
  fouroneone:
    container_name: fouroneone
    build: Fouroneone/
    networks:
    - fouroneone
    ports:
     - "80:80"

  mysql:
    container_name: mysql
    build:
      context: Mysql/
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fouroneone
      MYSQL_USER: fouroneone
      MYSQL_PASSWORD: fouroneone
    networks:
    - fouroneone
    volumes:
    - ./MySQL/sql/db_mysql.sql:/docker-entrypoint-initdb.d/01-fouroneoned_db.sql:ro
    ports:
    - "3306:3306"

networks:
  fouroneone:
    driver: bridge