version: '3'
services:
  fouroneoneweb:
    container_name: 411web
    build: 411-web/
    networks:
    - fouroneone
    ports:
     - "80:80"
    depends_on:
      - mysql

  fouroneonecron:
    container_name: 411cron
    build: 411-cron/
    networks:
      - fouroneone
    command:
      - '* * * * * /usr/bin/php /var/www/411/bin/cron.php  >>/var/log/cron.log 2>&1'
      - '* * * * * /usr/bin/php /var/www/411/bin/worker.php  >>/var/log/cron.log 2>&1'
#       - '* * * * * /usr/bin/php /var/www/411/bin/cron.php  >>/proc/$(cat /var/run/crond.pid)/fd/1 2>&1'
#       - '* * * * * /usr/bin/php /var/www/411/bin/worker.php  >>/proc/$(cat /var/run/crond.pid)/fd/1 2>&1'
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build:
      context: Mysql/
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fouroneone
      MYSQL_USER: fouroneone
      MYSQL_PASSWORD: fouroneone
    networks:
    - fouroneone
    volumes:
    - ./MySQL/sql/db_mysql.sql:/docker-entrypoint-initdb.d/01-fouroneoned_db.sql:ro
    ports:
    - "3306:3306"

networks:
  fouroneone:
    driver: bridge