version: '3'
services:
  fouroneone:
    build: Fouroneone/
    networks:
    - fouroneone
    ports:
     - "8080:80"

  mysql:
    container_name: mysql
    build:
      context: Mysql/
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fouroneone
      MYSQL_USER: fouroneone
      MYSQL_PASSWORD: samplepw
    networks:
    - fouroneone
    ports:
    - "3306:3306"
